### ISSUE TITLE
0.1.0 is yanked

### ISSUE THREAD

**Issue by etki** [ama-team/voxengine-scenario-framework#1]
https://travis-ci.org/ama-team/voxengine-scenario-framework/builds/202679590:

 82 passing (316ms)
  1 failing
  1) /execution /transition.js should correctly propagate transition rescue handler exception:
     AssertionError: expected 'TransitionTimeout' to equal 'TransitionFailed'
      at /home/travis/build/ama-team/voxengine-scenario-framework/test/spec/execution/transition.spec.js:175:24
      at runMicrotasksCallback (node.js:337:7)
      at process._tickCallback (node.js:355:11)

**Comment by etki** [comment]
So, what happened?

```
[WARN] ama-team.voxengine-scenario-framework.test.helper.common: Transition initialized -> terminated has exceeded timeout of 1 ms, launching rescue handler
[ERROR] ama-team.voxengine-scenario-framework.test.helper.common: Transition initialized -> terminated rescue handler has exceeded timeout of 1 ms
[ERROR] ama-team.voxengine-scenario-framework.test.helper.common: Transition initialized -> terminated rescue handler has finished with exception, propagating
[ERROR] ama-team.voxengine-scenario-framework.test.helper.common: Transition initialized -> terminated has completed with exception TimeoutException
  1) /execution /transition.js should correctly propagate transition rescue handler exception
    /execution /transition.js should not save timed out transition with timed out rescue handler: [DEBUG] ama-team.voxengine-scenario-framework.test.helper.common: Running Transition initialized -> terminated
```
From the log output, events seem to be in order: transitioned has failed to complete in time; rescue handler failed to complete in time; timeout trigger has worked out; rescue handler has finished right after that; system has confirmed that transition has finished with timeout.

So far so good, but this is kinda impossible with run-to-completion model and synchronous rescue handler. As soon as main transition handler fails, rescue handler is run wrapped in timeout; but in that exact case, rescue handler was synchronous, so timeout should haven't even had a chance to work out while process is busy running rescue handler.  
This is weird.

https://github.com/ama-team/voxengine-scenario-framework/blob/f2f9ef0d08fa664d42b3eeea524304726d2fda18/test/spec/execution/transition.spec.js#L155-L179

**Comment by etki** [comment]
What's been confirmed:
- Node 0.12 which has been used executes setTimeout in the same event loop (https://gist.github.com/etki/649cb2b43a6b0ed588e183cb98190388)
- Promise library used in tests doesn't use setTimeout in methods touched by VSF

Console printouts, however, may be out of order.

**Comment by etki** [comment]
Support for 0.1.0 has been dropped completely, issue and code will remain in tracker / repo, though it's not likely anyone will fix it
